group: travis_latest
dist: xenial  # ubuntu-16.04
language: python
cache: pip
python:
  - 3.6
  - 3.7
install:
  - pip install flake8
  - pip install -r requirements.txt
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  - true  # add other tests here
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
